# This file is for Netlify deploy button

[build]
  publish = "out/"
  command = "npm run export"

[template.environment]
  GITHUB_TOKEN = "You GitHub access token"

[context.production]
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }